language: ruby
dist: trusty
cache: bundler
sudo: required
env:
  - TEST_GROUP="cucumber -r features features/tags_and_wrangling -f Ao3Cucumber::Formatter --color"
rvm:
  - "2.2.5"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - travis_retry bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
notifications:
  email:
    recipients:
      - otw-coders-extra@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: change
   on_failure: change
